baseurl = "/"
title = "Singapore in numbers"
copyright = ""
canonifyurls = true
theme = "hugo-kiera"
googleAnalytics = "UA-110249030-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = ""
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[[menu.main]]
    name = "Home"
    url = "/"  
    weight = 1

[params]
    tagline = "Understanding Singapore through numbers, data, and statistics"


